### PR TITLE
feat: resolve #86

### LINKED ISSUE #86: Implement firebase auth to make security rule to allow only maker can create the order
This is done by 

- adding function to make the challenge
- sign by the challenge
- if signed properly, sign in with Firebase auth
- if the user change wallet, the firebase auth should be refreshed too

### PR DESCRIPTION
**Pull request by taijusanagi**
This include big file structure change.

common has entities
and the entities has a type, fixture, util
I did this because it is challenging to decide which package lib/logic belongs to.

So I make an entity, and all related to the entity should go to common.

### CODE REVIEW

**Comment by taijusanagi** [comment]
This include big file structure change.

- common has entities
- and the entities has a type, fixture, util

I did this because it is challenging to decide which package lib/logic belongs to.

So I make an entity, and all related to the entity should go to common.

**Comment by taijusanagi** [comment]
Please review @ksuhara @Aqrare 

for this reason
https://github.com/kaguraswap/monorepo/pull/122#issuecomment-1178478371

**Comment by ksuhara** [comment]
lgtm for the code.

my understanding is the code changes is not related to #86 but close it because we decided to go no auth

**Comment by taijusanagi** [comment]
yes, I just implement server logic for create order, and no user create from frontend, so no auth, then #86 is closed.

**Pull request merged**
