### PR TITLE
fix: improve loader

### LINKED ISSUE #262: Improve Loading
## Overview
- currently loading is only showing same data
- loading text needs better view

### PR DESCRIPTION
**Pull request by ksuhara**
close #262 

https://user-images.githubusercontent.com/45842611/180358869-7d1fcc0b-6df1-4274-ba38-8278c2a42cfb.mov

### CODE REVIEW

**Comment by taijusanagi** [comment]
let me check preview!

**Comment by taijusanagi** [comment]
looks nice!

loading design and limit control can be improved, but let's merge for now!

**Comment by taijusanagi** [comment]
@ksuhara 
Hi why removed 
vercel.json

**Comment by taijusanagi** [comment]
That is required so I recover in my branch

**Comment by ksuhara** [comment]
sorry, not intended

**Pull request merged**
